/* ══════════════════════════════════════════════════════════════════════════
   Promptwrought — the year in 52 words

   GENERATED FILE — do not edit by hand. tools/build-lexicon.py writes it
   from issues/*.json. Edit the issue file and run the script; anything
   typed straight in here is overwritten without warning.

   One object per week of 2026. `week` is the ISO week number and
   `releaseDate` its Tuesday. Neither ever changes, so the tray is built
   from them whether or not a word has been struck yet.

   A slot with an empty `word` renders as blank — a week before the run
   began, or one that was skipped — or as sealed, a week still to come.
   app.js decides by comparing `releaseDate` with today.

   Issue number and week differ by 30: issue 001 is week 031.

       week         ISO week of 2026, 1–52
       releaseDate  the Tuesday of that week, YYYY-MM-DD
       word         the headword; empty until the issue ships
       pos          part of speech, written out — "noun", "noun & verb"
       definition   the sense line, as it reads on the site
       tag          the category chip, e.g. "Asking", "Keeping"
       note         optional editor's aside, shown under the definition
       issueUrl     link to the Substack issue; omitted if empty

   `definition` and `note` are HTML fragments, as in issues/*.json — <em>
   works. The rest are plain text.
   ══════════════════════════════════════════════════════════════════════════ */

const WORDS = [
  {
    week: 1,
    releaseDate: "2025-12-30",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 2,
    releaseDate: "2026-01-06",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 3,
    releaseDate: "2026-01-13",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 4,
    releaseDate: "2026-01-20",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 5,
    releaseDate: "2026-01-27",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 6,
    releaseDate: "2026-02-03",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 7,
    releaseDate: "2026-02-10",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 8,
    releaseDate: "2026-02-17",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 9,
    releaseDate: "2026-02-24",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 10,
    releaseDate: "2026-03-03",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 11,
    releaseDate: "2026-03-10",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 12,
    releaseDate: "2026-03-17",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 13,
    releaseDate: "2026-03-24",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 14,
    releaseDate: "2026-03-31",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 15,
    releaseDate: "2026-04-07",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 16,
    releaseDate: "2026-04-14",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 17,
    releaseDate: "2026-04-21",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 18,
    releaseDate: "2026-04-28",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 19,
    releaseDate: "2026-05-05",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 20,
    releaseDate: "2026-05-12",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 21,
    releaseDate: "2026-05-19",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 22,
    releaseDate: "2026-05-26",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 23,
    releaseDate: "2026-06-02",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 24,
    releaseDate: "2026-06-09",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 25,
    releaseDate: "2026-06-16",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 26,
    releaseDate: "2026-06-23",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 27,
    releaseDate: "2026-06-30",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 28,
    releaseDate: "2026-07-07",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 29,
    releaseDate: "2026-07-14",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 30,
    releaseDate: "2026-07-21",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 31,
    releaseDate: "2026-07-28",
    word: "misask",
    pos: "noun & verb",
    definition: "The gap between what one asked for and what one meant; to instruct a machine accurately in the wrong direction.",
    tag: "Asking",
    note: "",
    issueUrl: "https://promptwrought.substack.com/p/misask",
  },
  {
    week: 32,
    releaseDate: "2026-08-04",
    word: "promptbook",
    pos: "noun",
    definition: "A personal, accumulated collection of proven instructions, kept and refined the way a cook keeps recipes; a promptwright’s working grimoire.",
    tag: "Keeping",
    note: "",
    issueUrl: "https://promptwrought.substack.com/p/promptbook",
  },
  {
    week: 33,
    releaseDate: "2026-08-11",
    word: "overwright",
    pos: "verb",
    definition: "To keep refining an instruction past the point of improvement; to polish a working prompt until it breaks.",
    tag: "Making",
    note: "",
    issueUrl: "https://promptwrought.substack.com/p/overwright",
  },
  {
    week: 34,
    releaseDate: "2026-08-18",
    word: "grainsense",
    pos: "noun",
    definition: "A practised feel for a particular machine’s tendencies — where it drifts, what it over-does, which phrasings it obeys; the promptwright’s knowledge of the material.",
    tag: "Knowing",
    note: "",
    issueUrl: "https://promptwrought.substack.com/p/grainsense",
  },
  {
    week: 35,
    releaseDate: "2026-08-25",
    word: "promptwright",
    pos: "noun",
    definition: "A person skilled in the craft of writing and refining instructions for generative AI systems to produce a reliable, intended result; a professional prompt-maker.",
    tag: "Naming",
    note: "",
    issueUrl: "https://promptwrought.substack.com/p/promptwright",
  },
  {
    week: 36,
    releaseDate: "2026-09-01",
    word: "beigevoice",
    pos: "noun",
    definition: "The default register of machine prose: affable, tidy, featureless; the sound of no one in particular.",
    tag: "Hearing",
    note: "",
    issueUrl: "https://promptwrought.substack.com/p/beigevoice",
  },
  {
    week: 37,
    releaseDate: "2026-09-08",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 38,
    releaseDate: "2026-09-15",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 39,
    releaseDate: "2026-09-22",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 40,
    releaseDate: "2026-09-29",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 41,
    releaseDate: "2026-10-06",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 42,
    releaseDate: "2026-10-13",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 43,
    releaseDate: "2026-10-20",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 44,
    releaseDate: "2026-10-27",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 45,
    releaseDate: "2026-11-03",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 46,
    releaseDate: "2026-11-10",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 47,
    releaseDate: "2026-11-17",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 48,
    releaseDate: "2026-11-24",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 49,
    releaseDate: "2026-12-01",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 50,
    releaseDate: "2026-12-08",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 51,
    releaseDate: "2026-12-15",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
  {
    week: 52,
    releaseDate: "2026-12-22",
    word: "",
    pos: "",
    definition: "",
    tag: "",
    note: "",
    issueUrl: "",
  },
];
